{
 "title": "AS Piranha Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Publisher Message Delivery Metrics (PiranhaEventPublisher Metrics",
   "type": "stat",
   "description": "This dashboard monitors the total number of messages published, publish failures, and the overall success rate of message delivery. It helps track publisher reliability and identify potential issues affecting message throughput.\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum((publisher_messages_published_total))\r\n/\r\n(\r\n  sum((publisher_messages_published_total)) + sum((publisher_publish_failures_total))\r\n)",
     "legendFormat": "Ratio between published and failure messages"
    },
    {
     "expr": "publisher_messages_published_total",
     "legendFormat": "Publisher Messages Published"
    },
    {
     "expr": "publisher_publish_failures_total",
     "legendFormat": "Publisher Messages Failures"
    }
   ]
  },
  {
   "title": "Recebed Messages (ExternelEventListenerService Metrics))",
   "type": "timeseries",
   "description": "All type os messages recebed \n\n✅ Acked\n❌ Nacked\n📦 Dead-lettered\n🧾 Invalid JSON\n🔐 Invalid Signature\n📜 Invalid Schema",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "listener_messages_acked_total", "legendFormat": "Total Acked Messages" },
    { "expr": "listener_messages_nacked_total", "legendFormat": "Total Nacked Messages" },
    {
     "expr": "listener_messages_deadlettered_total",
     "legendFormat": "Total Dead Lettered Messages"
    },
    {
     "expr": "listener_messages_invalid_json_total",
     "legendFormat": "Total Invalid JSON Messages"
    },
    {
     "expr": "listener_messages_invalid_signature_total",
     "legendFormat": "Total Invalid Signature Messages"
    },
    {
     "expr": "listener_messages_schema_invalid_total",
     "legendFormat": "Total Schema Invalid Messages"
    }
   ]
  },
  {
   "title": "Percentage of invalid messages (ExternalEventListenerService Metrics)",
   "type": "gauge",
   "description": "Percentages of invalid messages in relation to messages received\n\nTypes of Messages:\n\nInvalid JSON Messages\nInvalid Signatures Messages\nInvalid Schema Messages",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(listener_messages_invalid_json_total) / sum(listener_messages_received_total)",
     "legendFormat": "% of Invalid JSON Messages"
    },
    {
     "expr": "100 * sum(listener_messages_invalid_signature_total) / sum(listener_messages_received_total)",
     "legendFormat": "% of Invalid Signature Messages "
    },
    {
     "expr": "100 * sum(listener_messages_schema_invalid_total) / sum(listener_messages_received_total)",
     "legendFormat": "% of Invalid Schema Messages"
    }
   ]
  },
  {
   "title": "Processing success rate (ExternalEventListeningService Metrics)",
   "type": "stat",
   "description": "Ratio between all received messages and all acked messages\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(listener_messages_acked_total)\r\n/\r\n(sum(listener_messages_received_total) + 1e-9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Message processing time (ExternelEventListenerService Metrics)",
   "type": "timeseries",
   "description": "Average Message processing time (ExternelEventListenerService)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(listener_message_processing_duration_seconds_sum[100m]) \r\n/ \r\nrate(listener_message_processing_duration_seconds_count[100m])",
     "legendFormat": "Average processing time"
    }
   ]
  },
  {
   "title": "Events processed by type (ExternalEventListener Metrics)",
   "type": "piechart",
   "description": "Events processed by type (ExternalEventListener Metrics)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "listener_events_processed_total",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RabbitMQ System Health (RabbitMQ Metrics)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "listener_consumer_active", "legendFormat": "RabbitMQ State" },
    { "expr": "rabbitmq_connections", "legendFormat": "RabbitMQ Connections" },
    { "expr": "rabbitmq_channels", "legendFormat": "RabbitMQ Channels" }
   ]
  },
  {
   "title": " Page Actions Dashboard (API Controller Metrics)",
   "type": "piechart",
   "description": "Page Actions Dashboard to  show the request from the Page API Controller (Outbound event messaging)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "page_save_requests_total", "legendFormat": "New Content Request" },
    { "expr": "page_save_draft_requests_total", "legendFormat": "Save Draft Request" },
    { "expr": "page_delete_requests_total", "legendFormat": "Delete Request" }
   ]
  },
  {
   "title": "Publication Dashboard with Success Rate (PageAPIController Metrics)",
   "type": "gauge",
   "description": "Publication Dashboard with Success Rate for every type os request",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(page_save_draft_publish_success_total)\r\n/\r\n(sum(page_save_draft_publish_success_total) + sum(page_save_draft_publish_failure_total))",
     "legendFormat": "% of Sucess (Update Request)"
    },
    {
     "expr": "100 * sum(page_save_publish_success_total)\r\n/\r\n(sum(page_save_publish_success_total) + sum(page_save_publish_failure_total))",
     "legendFormat": "% of Sucess (New Content Request)"
    },
    {
     "expr": "100 * sum(page_delete_event_success_total)\r\n/\r\n(sum(page_delete_event_success_total) + sum(page_delete_event_failure_total))\r\n",
     "legendFormat": "% of Sucess (Delete Request)"
    }
   ]
  }
 ]
}