global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'piranha_app'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']
